nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*'] # Autorise toutes les sources (Angular, Mobile, etc.)
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*'] # Autorise tous les headers (Content-Type, Authorization, etc.)
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600