<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419154951 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, denomination VARCHAR(1) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_commande DATE NOT NULL, prix NUMERIC(15, 2) NOT NULL, delai_min SMALLINT DEFAULT NULL, delai_max SMALLINT DEFAULT NULL, statut VARCHAR(50) NOT NULL, fournisseur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D670C757F ON commande (fournisseur_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, telephone VARCHAR(50) DEFAULT NULL, mail VARCHAR(50) DEFAULT NULL, statut VARCHAR(50) DEFAULT NULL, date_maj DATE DEFAULT NULL, fonction_id INT DEFAULT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E63857889920 ON contact (fonction_id)');
        $this->addSql('CREATE INDEX IDX_4C62E638670C757F ON contact (fournisseur_id)');
        $this->addSql('CREATE TABLE contenir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, commande_id INT NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3C914DFD82EA2E54 ON contenir (commande_id)');
        $this->addSql('CREATE INDEX IDX_3C914DFDF347EFB ON contenir (produit_id)');
        $this->addSql('CREATE TABLE fonction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fournis_par (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prix NUMERIC(15, 2) NOT NULL, moq NUMERIC(15, 2) NOT NULL, produit_id INT NOT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8396C7AF347EFB ON fournis_par (produit_id)');
        $this->addSql('CREATE INDEX IDX_E8396C7A670C757F ON fournis_par (fournisseur_id)');
        $this->addSql('CREATE TABLE fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, telephone VARCHAR(50) DEFAULT NULL, adresse VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE inventaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_inv DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, poids NUMERIC(15, 2) DEFAULT NULL, quantite INT NOT NULL, date_peremption DATE NOT NULL, date_entree_lot DATE NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_916087CEF347EFB ON lots (produit_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, nom_scientifique VARCHAR(50) NOT NULL, fonction VARCHAR(50) DEFAULT NULL, cosmos VARCHAR(150) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE recu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, date_reception DATE NOT NULL, commande_id INT NOT NULL, lot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C0D1031782EA2E54 ON recu (commande_id)');
        $this->addSql('CREATE INDEX IDX_C0D10317A8CBA5F7 ON recu (lot_id)');
        $this->addSql('CREATE TABLE verifier_lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, inventaire_id INT NOT NULL, lot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2772D8EACE430A85 ON verifier_lot (inventaire_id)');
        $this->addSql('CREATE INDEX IDX_2772D8EAA8CBA5F7 ON verifier_lot (lot_id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63857889920 FOREIGN KEY (fonction_id) REFERENCES fonction (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contenir ADD CONSTRAINT FK_3C914DFD82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contenir ADD CONSTRAINT FK_3C914DFDF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournis_par ADD CONSTRAINT FK_E8396C7AF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournis_par ADD CONSTRAINT FK_E8396C7A670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lots ADD CONSTRAINT FK_916087CEF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recu ADD CONSTRAINT FK_C0D1031782EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recu ADD CONSTRAINT FK_C0D10317A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lots (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verifier_lot ADD CONSTRAINT FK_2772D8EACE430A85 FOREIGN KEY (inventaire_id) REFERENCES inventaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verifier_lot ADD CONSTRAINT FK_2772D8EAA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lots (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D670C757F');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E63857889920');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638670C757F');
        $this->addSql('ALTER TABLE contenir DROP CONSTRAINT FK_3C914DFD82EA2E54');
        $this->addSql('ALTER TABLE contenir DROP CONSTRAINT FK_3C914DFDF347EFB');
        $this->addSql('ALTER TABLE fournis_par DROP CONSTRAINT FK_E8396C7AF347EFB');
        $this->addSql('ALTER TABLE fournis_par DROP CONSTRAINT FK_E8396C7A670C757F');
        $this->addSql('ALTER TABLE lots DROP CONSTRAINT FK_916087CEF347EFB');
        $this->addSql('ALTER TABLE recu DROP CONSTRAINT FK_C0D1031782EA2E54');
        $this->addSql('ALTER TABLE recu DROP CONSTRAINT FK_C0D10317A8CBA5F7');
        $this->addSql('ALTER TABLE verifier_lot DROP CONSTRAINT FK_2772D8EACE430A85');
        $this->addSql('ALTER TABLE verifier_lot DROP CONSTRAINT FK_2772D8EAA8CBA5F7');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contenir');
        $this->addSql('DROP TABLE fonction');
        $this->addSql('DROP TABLE fournis_par');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE inventaire');
        $this->addSql('DROP TABLE lots');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE recu');
        $this->addSql('DROP TABLE verifier_lot');
    }
}
