<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328160027 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, denomination VARCHAR(1) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fournis_par (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prix NUMERIC(15, 2) DEFAULT NULL, moq NUMERIC(15, 2) DEFAULT NULL, produit_id INT NOT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8396C7AF347EFB ON fournis_par (produit_id)');
        $this->addSql('CREATE INDEX IDX_E8396C7A670C757F ON fournis_par (fournisseur_id)');
        $this->addSql('CREATE TABLE fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, telephone VARCHAR(50) DEFAULT NULL, adresse VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE inventaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_inv DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, poids NUMERIC(15, 2) DEFAULT NULL, quantite INT NOT NULL, date_peremption DATE NOT NULL, date_entree_lot DATE NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_916087CEF347EFB ON lots (produit_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, nom_scientifique VARCHAR(50) NOT NULL, fonction VARCHAR(50) DEFAULT NULL, cosmos VARCHAR(150) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE verifier_lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, inventaire_id INT NOT NULL, lot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2772D8EACE430A85 ON verifier_lot (inventaire_id)');
        $this->addSql('CREATE INDEX IDX_2772D8EAA8CBA5F7 ON verifier_lot (lot_id)');
        $this->addSql('ALTER TABLE fournis_par ADD CONSTRAINT FK_E8396C7AF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournis_par ADD CONSTRAINT FK_E8396C7A670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lots ADD CONSTRAINT FK_916087CEF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verifier_lot ADD CONSTRAINT FK_2772D8EACE430A85 FOREIGN KEY (inventaire_id) REFERENCES inventaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verifier_lot ADD CONSTRAINT FK_2772D8EAA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lots (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fournis_par DROP CONSTRAINT FK_E8396C7AF347EFB');
        $this->addSql('ALTER TABLE fournis_par DROP CONSTRAINT FK_E8396C7A670C757F');
        $this->addSql('ALTER TABLE lots DROP CONSTRAINT FK_916087CEF347EFB');
        $this->addSql('ALTER TABLE verifier_lot DROP CONSTRAINT FK_2772D8EACE430A85');
        $this->addSql('ALTER TABLE verifier_lot DROP CONSTRAINT FK_2772D8EAA8CBA5F7');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE fournis_par');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE inventaire');
        $this->addSql('DROP TABLE lots');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE verifier_lot');
    }
}
